


class EnvConfigTest():

    MAIN_HOSTNAME = 'YOUR HOST NAME'
    MAIN_DATABASE = 'YOUR DATABASE NAME'
    DATABASE_USERNAME = 'YOUR DATABASE USERNAME'
    DATABASE_PASSWORD = 'YOUR DATABASE PASSWORD'
    DATABASE_PORT_ID = 'YOUR PORT ID'
    ENCRYPT_DATABASE = 'YOUR DATABASE NAME'
    COBRA_EMAIL = "YOUR EMAIL "
    SMTP_SERVER = "YOUR SMTP SERVER"
    EMAIL_PASSWORD = 'YOUR EMAIL PASSWORD'